FROM nginx
MAINTAINER alexji.dev@gmail.com
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./upstream.conf /etc/nginx/conf.d/upstream.conf
ENV DEBCONF_NOWARNINGS yes
RUN apt-get update -y
RUN apt-get install vim -y
VOLUME /var/log/nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
