FROM openjdk:8-jdk-alpine
MAINTAINER alexji.dev@gmail.com
EXPOSE 8080
ARG JAR_FILE=./build/libs/automart-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} automart-app.jar
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=real","/automart-app.jar"]